name: IaC for AKS

on:
  push:
    branches: [ main ]
    paths: [ "iac/**" ]
    
  pull_request:
    branches: [ main ]
    paths: [ "iac/**" ]

  workflow_dispatch:

env:
  RESOURCE_GROUP: devops-showoff

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create Resource Group
      - name: resource group
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group create -n ${{ env.RESOURCE_GROUP }} -l eastus2

      # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./iac/main.bicep
          parameters: clusterName=devopsshowoff01
          failOnStdErr: false
